name: "Terraform Destroy"

on:
    workflow_dispatch:

jobs:
    terraform:
        name: "Terraform Destroy"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configurar as credenciais da AWS
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{  secrets.AWS_ACCESS_KEY_ID  }}
                aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY_ID  }}
                aws-region: us-east-1
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
               terraform_version: 1.12.2

            - name: Terraform Init
              working-directory: ./src
              run: terraform init -backend-config="bucket=${{  secrets.AWS_BUCKET_NAME  }}" -backend-config="key=${{  secrets.AWS_BUCKET_FILE  }}"

            - name: Terraform Destroy
              working-directory: ./src
              run: terraform destroy --auto-approve